# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b2aa0b7994c2b1e4cf4dbfe939144c6196bfaab402b0bf06d63eb8f9a2643aee737db64ecbd5506d0a0334bc69546f145818131541554b36bc8e667c3d6ad05

test:
  secret_key_base: ee342a6657ed4cc9e5c5878db3621a7a8795d0578f7ff1f71ec6913b598c765450a13c0b6a6ed67e0002582c4b0ead5bceca07dc029b37f0191be9653f232bda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
